# Generated by Django 4.2.5 on 2023-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.CharField(default='abc', max_length=100, unique=True)),
                ('full_name', models.CharField(default='abc', max_length=100)),
                ('Primary_PhoneNum', models.IntegerField(default=0)),
                ('Alternative_Phonenum', models.IntegerField(default=0)),
                ('Email_Id', models.EmailField(default='abc@gmail.com', max_length=150)),
                ('profession', models.CharField(default=0, max_length=150)),
                ('Location', models.CharField(default=0, max_length=150)),
            ],
        ),
    ]
